package document

import (
	"context"
	"errors"
	"io"
)

var (
	// ErrInvalidKey indicates that a storage key is empty, malformed, or
	// attempts to escape the configured document-storage namespace.
	ErrInvalidKey = errors.New("invalid document storage key")

	// ErrNotFound indicates that the requested stored object does not exist.
	ErrNotFound = errors.New("document object not found")
)

// PutRequest describes a document binary that must be written to storage.
//
// Key is generated by trusted server-side application code. Implementations
// must still validate it because storage boundaries must not rely solely on
// their callers for path safety.
type PutRequest struct {
	Key  string
	Body io.Reader
}

// Storage is the binary-storage boundary for regulatory driver documents.
//
// Database metadata is deliberately outside this interface. Storage owns only
// document bytes identified by opaque server-generated keys.
type Storage interface {
	Put(
		ctx context.Context,
		req PutRequest,
	) error

	Delete(
		ctx context.Context,
		key string,
	) error
}
